### ISSUE TITLE
cannot find './helper/debug'

### ISSUE THREAD

**Issue by nkappler** [legend80s/es5-validator#1]
When I try running it via npx I get the following output:

```
npx: installed 44 in 1.53s
Cannot find module './helper/debug'
Require stack:
- C:\Users\Nikolaj\AppData\Roaming\npm-cache\_npx\18536\node_modules\es5-validator\index.js
```

**Comment by nkappler** [comment]
It works with `npx es5-validation@1.1 ...` so it seems to be a regression
